runtime: nodejs10 # For Node.js 8, use runtime: nodejs8
instance_class: F1

automatic_scaling:  
 min_instances: 0
 max_instances: 1
 min_idle_instances: 0
 max_idle_instances: 1
 target_cpu_utilization: .95
 max_concurrent_requests: 80
 min_pending_latency: 15s
 max_pending_latency: 15s
 