npm install --save react-native@0.59.9
npm install --save react-native-animated-bar@0.2.0
npm install --save react-native-ble-manager@6.6.8
npm install --save react-native-cli@2.0.1
npm install --save react-native-flip-toggle-button@1.0.5
npm install --save react-native-fs@2.13.3
npm install --save react-native-modal-dropdown@0.6.2
npm install --save react-native-platform-touchable@1.1.1
npm install --save react-native-slider@0.11.0
npm install --save react-native-vector-icons@6.6.0
npm install --save react-native-wheel-picker@1.2.0 
npm install --save @mapbox/geo-viewport@0.4.0",
npm install --save @react-native-community/async-storage@1.5.1
npm install --save @react-native-mapbox-gl/maps@7.0.0-rc3
npm install --save async-mutex@0.1.3
npm install --save buffer@5.2.1
npm install --save charenc@0.0.2
npm install --save convert-string@0.1.0
npm install --save-dev babel-eslint@10.0.2 
npm install --save-dev eslint@6.0.1 
npm install --save-dev eslint-config-google@0.13.0 
npm install --save-dev eslint-plugin-react@7.14.2 
npm install --save-dev eslint-plugin-react-native@3.7.0 
npm install --save-dev metro-react-native-babel-preset@0.55.0 
npm install --save-dev react-native-scripts@2.0.1 